[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.8.2"

[[constraint]]
  branch = "master"
  name = "github.com/cppforlife/cobrautil"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "go.starlark.net"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[prune]
  go-tests = true
  unused-packages = true
