#@ def yamlfunc():
key: #@ textfunc()
#@ end

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    #! TODO stacktrace is still not correct
    test3: |
      (@- def textfunc(): @)(@= 1+"1" @)(@ end -@)
      fromtext=(@= yamlfunc() @)

+++

ERR: 
- unknown binary op: int + string
    in textfunc
      stdin:10 | = 1+"1" 
    in yamlfunc
      stdin:2 | key: #@ textfunc()
    in <toplevel>
      stdin:11 | = yamlfunc() 